# Generated by Django 5.1.3 on 2024-12-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(default='logos/usergenerics.png', upload_to='logos/', verbose_name='Cargar Logo'),
        ),
    ]
