FROM python:3.9-slim

WORKDIR /app

# Copiar el archivo de requerimientos
COPY requirements.txt .

# Instalar dependencias
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copiar TODO el proyecto (incluyendo manage.py y todos los directorios)
COPY . /app/

EXPOSE 8000

# Arrancar el servidor de Django utilizando el manage.py que se encuentra
# en el directorio backend
CMD ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]

