# Generated by Django 5.1.3 on 2024-12-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'verbose_name_plural': 'perfiles'},
        ),
    ]
