# Generated by Django 5.1.3 on 2024-12-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nit',
            field=models.IntegerField(blank=True, null=True, verbose_name='NIT'),
        ),
    ]
